services:
  - type: web
    name: traffic-bot-1
    env: node
    buildCommand: npm install
    startCommand: node auto-clicker-bot.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
